import type { Card } from "./types/Card.js";

export const MAX_GAMES = 50;
export const MIN_PLAYERS = 2;
export const MAX_PLAYERS = 10;
export const INITIAL_HAND_SIZE = 7;
export const ACTION_CARD_VALUE = 20;
export const WILD_CARD_VALUE = 50;

export const CARDS: readonly Card[] = [
  { color: "red", type: "number", value: 0, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "red", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "red", type: "drawTwo", id: crypto.randomUUID() },
  { color: "red", type: "drawTwo", id: crypto.randomUUID() },
  { color: "red", type: "reverse", id: crypto.randomUUID() },
  { color: "red", type: "reverse", id: crypto.randomUUID() },
  { color: "red", type: "skip", id: crypto.randomUUID() },
  { color: "red", type: "skip", id: crypto.randomUUID() },

  { color: "yellow", type: "number", value: 0, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "yellow", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "yellow", type: "drawTwo", id: crypto.randomUUID() },
  { color: "yellow", type: "drawTwo", id: crypto.randomUUID() },
  { color: "yellow", type: "reverse", id: crypto.randomUUID() },
  { color: "yellow", type: "reverse", id: crypto.randomUUID() },
  { color: "yellow", type: "skip", id: crypto.randomUUID() },
  { color: "yellow", type: "skip", id: crypto.randomUUID() },

  { color: "green", type: "number", value: 0, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "green", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "green", type: "drawTwo", id: crypto.randomUUID() },
  { color: "green", type: "drawTwo", id: crypto.randomUUID() },
  { color: "green", type: "reverse", id: crypto.randomUUID() },
  { color: "green", type: "reverse", id: crypto.randomUUID() },
  { color: "green", type: "skip", id: crypto.randomUUID() },
  { color: "green", type: "skip", id: crypto.randomUUID() },

  { color: "blue", type: "number", value: 0, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 1, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 2, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 3, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 4, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 5, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 6, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 7, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 8, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "blue", type: "number", value: 9, id: crypto.randomUUID() },
  { color: "blue", type: "drawTwo", id: crypto.randomUUID() },
  { color: "blue", type: "drawTwo", id: crypto.randomUUID() },
  { color: "blue", type: "reverse", id: crypto.randomUUID() },
  { color: "blue", type: "reverse", id: crypto.randomUUID() },
  { color: "blue", type: "skip", id: crypto.randomUUID() },
  { color: "blue", type: "skip", id: crypto.randomUUID() },

  { type: "wild", isDrawFour: false, id: crypto.randomUUID() },
  { type: "wild", isDrawFour: false, id: crypto.randomUUID() },
  { type: "wild", isDrawFour: false, id: crypto.randomUUID() },
  { type: "wild", isDrawFour: false, id: crypto.randomUUID() },

  { type: "wild", isDrawFour: true, id: crypto.randomUUID() },
  { type: "wild", isDrawFour: true, id: crypto.randomUUID() },
  { type: "wild", isDrawFour: true, id: crypto.randomUUID() },
  { type: "wild", isDrawFour: true, id: crypto.randomUUID() },
];
